services:
  backend:
    image: backend
    environment:
      - "MONGODB_URI=${MONGODB_URI}"
      - "JWT_SECRET=${JWT_SECRET}"
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: backend
    mem_limit: "333m"
    memswap_limit: "1024m"
    mem_swappiness: 60
  app:
    image: frontend
    environment:
      - BACKEND_URL=http://localhost:8080/api
      - NODE_ENV=production
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    container_name: frontend
    mem_limit: "333m"
    memswap_limit: "1024m"
    mem_swappiness: 60
    depends_on:
      - backend
  nginx:
    image: nginx:1.23.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    mem_limit: 200m
    memswap_limit: 1024m
    mem_swappiness: 60
    depends_on:
      - app
  debug-helper:
    image: busybox
