name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Clean up
        run: |
          rm -rf backend/node_modules
          rm -rf frontend/node_modules
      - name: Add secrets for deployment
        run: |
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "${{ secrets.ID_RSA }}" > backend/id_rsa
          echo "${{ secrets.ID_RSA_PUB }}" > backend/id_rsa.pub
      - name: Deploy to server
        uses: Ma100Dev/github-action-ssh-docker-compose@master # Not recommended to use master
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_host: ${{ secrets.SSH_HOST }}
          ssh_user: ${{ secrets.SSH_USER }}
          docker_compose_prefix: production
          docker_compose_filename: docker-compose.yml
      - name: URL Health Check
        uses: Jtalk/url-health-check-action@v2.3
        with:
          url: http://144.126.245.231:8080/api/properties|http://144.126.245.231:8080/
          follow-redirect: true
          max-attempts: 3
          retry-delay: 10s
          retry-all: true
      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@master # Not recommended to use master
        with:
          CLOSE_ISSUES: true
          AUTO_ASSIGN: true
        id: "todo"
