name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          length: 7
      - name: Add .env for deployment
        run: |
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
      - uses: matiasnu/github-action-ssh-docker-compose@master
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_host: ${{ secrets.SSH_HOST }}
          ssh_user: ${{ secrets.SSH_USER }}
          docker_compose_prefix: production
          docker_compose_filename: docker-compose.yml
      - name: URL Health Check
        uses: Jtalk/url-health-check-action@v2.2
        with:
          url: http://144.126.245.231:8080/api/properties|http://144.126.245.231:8080/
          follow-redirect: true
          max-attempts: 3
          retry-delay: 10s
          retry-all: true
