name: Validation pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  checkPipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install Yarn
        run: npm install -g yarn
      - name: Prepare backend
        run: |
          cd backend
          rm -rf node_modules
          yarn install --immutable --immutable-cache --check-cache
          yarn run generateKeys
      - name: Prepare frontend
        run: |
          cd frontend
          rm -rf node_modules
          yarn install --immutable --immutable-cache --check-cache
      - name: Lint frontend
        run: |
          cd frontend
          yarn run lint
      - name: Build frontend
        run: |
          cd frontend
          yarn run build
      - name: Lint backend
        run: |
          cd backend
          yarn run lint
      - name: Test backend db
        run: |
          cd backend
          export MONGOMS_VERSION=6.0.3
          export MONGOMS_DOWNLOAD_URL=https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2004-6.0.3.tgz
          export POPULATE_DB=true
          export NO_RUN=true
          yarn
          yarn start
      - name: Frontend E2E tests
        uses: cypress-io/github-action@v5
        with:
          command: yarn run cypress:run
          install: false
          working-directory: frontend
          start: yarn run start:test
          wait-on: http://localhost:3000
      - uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: cypress-videos
          path: frontend/cypress/videos/
